### ISSUE TITLE
Installation issue with Phoenix 1.3.0-RC

### ISSUE THREAD

**Issue by dhruvbhatia** [opendrops/passport#36]
Hi there,

I'm attempting to [follow Passport's installation instructions for use with Phoenix 1.3.0-RC as per the readme](https://github.com/opendrops/passport#installation-and-usage), however get stuck at the last step:

```bash
> mix passport.setup

** (UndefinedFunctionError) function Mix.Tasks.Phx.Gen.Html.build/1 is undefined or private
    Mix.Tasks.Phx.Gen.Html.build(["Account", "User", "users"])
    lib/mix/tasks/passport.setup.ex:23: Mix.Tasks.Passport.Setup.generate_account/1
    lib/mix/tasks/passport.setup.ex:13: Mix.Tasks.Passport.Setup.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Any ideas on what the above means?
I'm an Elixir newbie using `Elixir 1.4.2` and `{:phoenix, "~> 1.3.0-rc"}`.
Help appreciated! 👍

**Comment by elpikel** [comment]
I just created pull request that should fix this issue.

**Comment by Virviil** [comment]
`{:passport, git: "https://github.com/elpikel/passport", branch: "Installation-issue-with-Phoenix-1.3.0-RC"}`

in deps 

and get the same issue

**Comment by Virviil** [comment]
https://github.com/phoenixframework/phoenix/blob/v1.3.0-rc.2/lib/mix/tasks/phx.gen.html.ex

`Mix.Tasks.Phx.Gen.Html` doesn't have `build` function.

As I see that should be changed to `Mix.Tasks.Phx.Gen.Context`
